curl "http://localhost:9999/login/zhangsan" -X POST -d '{"user":"张三","passwd":"123456"}' --header "Content-Type: application/json"
curl "http://localhost:9999/login/lisi/info" -X POST -d '{"user":"张三","passwd":"123456"}' --header "Content-Type: application/json"
curl "http://localhost:9999/login" -X POST -d '{"user":"李四","passwd":"qwert"}' --header "Content-Type: application/json"
curl "http://localhost:9999/login?user=axing&passwd=123456"
curl "http://localhost:9999/v1?user=axing&passwd=123456"
curl "http://localhost:9999/v1/user?user=axing&passwd=123456"
curl "http://localhost:9999/"
curl "http://localhost:9999"
curl "http://localhost:9999/file/file/anudoa/asfdnioap.xkx"
curl "http://localhost:9999/file/file/css/asfdnioap.xkx"
curl "http://localhost:9999/file/css/asfdnioap.xkx"
curl "http://localhost:9999/filsdsdse/css/asfdnioap.xkx"

